### ISSUE TITLE
some non-urgent ideas on built-in pypyr functionality

### ISSUE THREAD

**Issue by yaythomas** [fvutils/mkdv#1]
Hi, interesting project! Thanks for using pypyr! I've got a couple of suggestions that I hope _might_ make your life a little easier (I'm the creator/maintainer of pypyr 😄 )

1. The custom parser at [parser/default.py](https://github.com/fvutils/mkdv/tree/main/src/mkdv/parser/default.py) is pretty much doing the same thing as the built-in [pypyr.parser.keyvaluepairs](https://pypyr.io/docs/context-parsers/keyvaluepairs/) parser, so this might save you having to worry about the custom code. . .

2. The [pyrun](https://github.com/fvutils/mkdv/blob/main/src/mkdv/steps/pyrun.py) step you can achieve the same thing with the built-in [pypyr.steps.python](https://pypyr.io/docs/steps/python/) step to get the current sys.executable, so your pipelines would look like:
```yaml
steps:
  - pypyr.steps.python

  - name: pypyr.steps.cmd
    description: --> whatever modules you want to invoke
    in:
      cmd: '"{python}" -m arbpackage.mymodule --myarg' 
```
  You can of course use further {formatting expressions} to inject different package/module/args into the cmd.
```yaml
steps:
  - pypyr.steps.python

  - name: pypyr.steps.cmd
    description: --> pass whatever is in args to python -m.
    in:
      cmd: '"{python}" -m {args}' 
```

3. For [steps/entry.py](https://github.com/fvutils/mkdv/blob/main/src/mkdv/steps/entry.py) you could use the built-in [pypyr.steps.pype](https://pypyr.io/docs/steps/pype/) step to invoke child pipelines from a parent pipeline. You can use the `args` input on `pype` to initialise the child pipeline's context with specific values like `MKDV_CACHEDIR` and set `groups` to specify which groups to run (e.g `['setup', 'run']`).

4. A couple of the custom steps work with environment variables. pypyr has builtin [pypyr.steps.env](https://pypyr.io/docs/steps/env/) and [pypyr.steps.envget](https://pypyr.io/docs/steps/envget/) to allow you to get $VARs into context or set $VARS etc. This may or may not make your life easier, could also be that just doing it in custom step code is less laborious, depends on the particular circumstance.

Hope this helps! To be clear, nothing you're doing is "wrong" and of course it'll work and it could well even be necessary depending on longer term objectives you have in mind... I just thought to throw some casual suggestions your way in the hope that it might make your pypyr experience smooth as possible!

If you have feedback/suggestions/ideas for improvement on pypyr built-in functionality feel free to get in touch!
